dist: bionic
language: minimal
git:
  depth: false
  submodules: false
notifications:
  email: false

script: 
# wget -O cpsievert/plotly_book/DESCRIPTION https://github.com/cpsievert/plotly_book/raw/master/DESCRIPTION
# wget -O csgillespie/efficientR/DESCRIPTION https://github.com/csgillespie/efficientR/raw/master/DESCRIPTION
# wget -O hadley/adv-r/DESCRIPTION https://github.com/hadley/adv-r/raw/master/DESCRIPTION
# wget -O hadley/ggplot2-book/DESCRIPTION https://github.com/hadley/ggplot2-book/raw/master/DESCRIPTION
# wget -O hadley/mastering-shiny/DESCRIPTION https://github.com/hadley/mastering-shiny/raw/master/DESCRIPTION
# wget -O hadley/r4ds/DESCRIPTION https://github.com/hadley/r4ds/raw/master/DESCRIPTION
# wget -O hadley/r-pkgs/DESCRIPTION https://github.com/hadley/r-pkgs/raw/master/DESCRIPTION
# wget -O rstudio/bookdown-demo/DESCRIPTION https://github.com/rstudio/bookdown-demo/raw/master/DESCRIPTION
# wget -O tidyverse/design/DESCRIPTION https://github.com/tidyverse/design/raw/master/DESCRIPTION
# wget -O tidyverse/style/DESCRIPTION https://github.com/tidyverse/style/raw/master/DESCRIPTION
# wget -O tidyverse/tidyeval/DESCRIPTION https://github.com/tidyverse/tidyeval/raw/master/DESCRIPTION
# wget -O wch/rgcookbook/DESCRIPTION https://github.com/wch/rgcookbook/raw/master/DESCRIPTION
  - git remote set-url origin https://$GITHUB_PAT@github.com/$TRAVIS_REPO_SLUG.git
  - git reset master
  - git status
  - git add --all
  - git commit -m "Travis build at `date '+%Y-%m-%d %H:%M:%S'`" --allow-empty
  - git push -f


